from __future__ import annotations

import argparse
import hashlib
import json
import re
import shutil
from collections import Counter, defaultdict
from pathlib import Path, PurePosixPath
from typing import Any, Iterable

import yaml

from src.common import ROOT, read_jsonl, write_jsonl

DATASETS = ("files", "commits", "issues", "pulls")
WHITESPACE_RE = re.compile(r"[ \t]+")
BLANK_LINES_RE = re.compile(r"\n{3,}")
CONTROL_RE = re.compile(r"[\x00-\x08\x0b\x0c\x0e-\x1f\x7f]")
GENERATED_HINT_RE = re.compile(
    r"(?i)(auto[- ]?generated|generated by|do not edit|machine generated)"
)
MINIFIED_LINE_RE = re.compile(r"^.{5000,}$", re.MULTILINE)


def clean_text(value: Any, normalize_whitespace: bool = True) -> str:
    """Return safe, normalized UTF-8-like text without changing semantics."""
    if value is None:
        return ""
    text = str(value).replace("\r\n", "\n").replace("\r", "\n")
    text = CONTROL_RE.sub("", text).strip()
    if normalize_whitespace:
        text = "\n".join(WHITESPACE_RE.sub(" ", line).rstrip() for line in text.split("\n"))
        text = BLANK_LINES_RE.sub("\n\n", text)
    return text.strip()


def normalize_path(value: Any) -> str:
    text = clean_text(value, normalize_whitespace=False).replace("\\", "/")
    while "//" in text:
        text = text.replace("//", "/")
    text = text.lstrip("./")
    parts = [p for p in PurePosixPath(text).parts if p not in ("", ".")]
    if ".." in parts:
        return ""
    return "/".join(parts)


def canonical_file_id(repo: str, path: str) -> str:
    return f"{repo}:file:{path}"


def canonical_commit_id(repo: str, original_id: str) -> str:
    prefix = f"{repo}:commit:"
    return original_id if original_id.startswith(prefix) else f"{prefix}{original_id}"


def canonical_issue_id(repo: str, number: Any, original_id: str) -> str:
    return f"{repo}:issue:{number}" if number is not None else f"{repo}:issue:{original_id}"


def canonical_pr_id(repo: str, number: Any, original_id: str) -> str:
    return f"{repo}:pr:{number}" if number is not None else f"{repo}:pr:{original_id}"


def stable_fingerprint(record: dict[str, Any], fields: Iterable[str]) -> str:
    payload = {field: record.get(field) for field in fields}
    raw = json.dumps(payload, sort_keys=True, ensure_ascii=False, default=str)
    return hashlib.sha256(raw.encode("utf-8")).hexdigest()


def irrelevant_file(path: str, content: str, config: dict[str, Any]) -> tuple[bool, str]:
    p = PurePosixPath(path)
    lower_parts = {part.lower() for part in p.parts}
    excluded_dirs = {x.lower() for x in config.get("excluded_directories", [])}
    if lower_parts & excluded_dirs:
        return True, "excluded_directory"

    name = p.name.lower()
    if name in {x.lower() for x in config.get("excluded_filenames", [])}:
        return True, "excluded_filename"

    lower_path = path.lower()
    if any(lower_path.endswith(s.lower()) for s in config.get("excluded_suffixes", [])):
        return True, "excluded_suffix"

    encoded_size = len(content.encode("utf-8", errors="ignore"))
    if encoded_size > int(config.get("max_file_bytes", 200_000)):
        return True, "file_too_large"
    if len(content) < int(config.get("min_text_characters", 2)):
        return True, "empty_or_too_short"
    if MINIFIED_LINE_RE.search(content):
        return True, "likely_minified"

    # Generated files are excluded only when their path also signals generated output.
    generated_dirs = {"generated", "dist", "build", "target", "out"}
    if GENERATED_HINT_RE.search(content[:2000]) and lower_parts & generated_dirs:
        return True, "generated_artifact"
    return False, ""


def preprocess_files(rows: list[dict[str, Any]], config: dict[str, Any], stats: Counter) -> list[dict[str, Any]]:
    output: list[dict[str, Any]] = []
    seen_ids: set[str] = set()
    for row in rows:
        repo = clean_text(row.get("repo"))
        path = normalize_path(row.get("path"))
        content = clean_text(row.get("content"), bool(config.get("normalize_whitespace", True)))
        if not repo or not path:
            stats["files_missing_required"] += 1
            continue
        is_irrelevant, reason = irrelevant_file(path, content, config)
        if is_irrelevant:
            stats[f"files_{reason}"] += 1
            continue
        content = content[: int(config.get("max_text_characters", 120_000))]
        record = {
            "id": canonical_file_id(repo, path),
            "repo": repo,
            "path": path,
            "extension": PurePosixPath(path).suffix.lower(),
            "content": content,
        }
        if record["id"] in seen_ids:
            stats["files_duplicate_id"] += 1
            continue
        seen_ids.add(record["id"])
        output.append(record)
    return output


def preprocess_commits(rows: list[dict[str, Any]], config: dict[str, Any], stats: Counter) -> list[dict[str, Any]]:
    output: list[dict[str, Any]] = []
    seen_ids: set[str] = set()
    for row in rows:
        repo = clean_text(row.get("repo"))
        original_id = clean_text(row.get("id"))
        message = clean_text(row.get("message"))
        if not repo or not original_id or len(message) < int(config.get("min_commit_message_characters", 2)):
            stats["commits_missing_required"] += 1
            continue
        modified_files = []
        seen_paths: set[str] = set()
        for item in row.get("modified_files") or []:
            path = normalize_path(item.get("path"))
            if not path or path in seen_paths:
                stats["commit_duplicate_or_invalid_file_change"] += 1
                continue
            # Changes to ignored build/vendor paths do not create graph relationships.
            fake_content = "x" * 10
            ignored, _ = irrelevant_file(path, fake_content, config)
            if ignored:
                stats["commit_irrelevant_file_change"] += 1
                continue
            seen_paths.add(path)
            modified_files.append({
                "path": path,
                "file_id": canonical_file_id(repo, path),
                "added": max(0, int(item.get("added") or 0)),
                "deleted": max(0, int(item.get("deleted") or 0)),
            })
        record = {
            "id": canonical_commit_id(repo, original_id),
            "original_id": original_id,
            "repo": repo,
            "message": message,
            "timestamp": clean_text(row.get("timestamp"), normalize_whitespace=False),
            "author_name": clean_text(row.get("author_name")) or None,
            "author_email": clean_text(row.get("author_email")).lower() or None,
            "modified_files": modified_files,
        }
        if record["id"] in seen_ids:
            stats["commits_duplicate_id"] += 1
            continue
        seen_ids.add(record["id"])
        output.append(record)
    return output


def preprocess_issues(rows: list[dict[str, Any]], config: dict[str, Any], stats: Counter) -> list[dict[str, Any]]:
    output: list[dict[str, Any]] = []
    seen_ids: set[str] = set()
    seen_fingerprints: set[str] = set()
    for row in rows:
        repo = clean_text(row.get("repo"))
        number = row.get("number")
        title = clean_text(row.get("title"))
        if not repo or len(title) < int(config.get("min_issue_title_characters", 2)):
            stats["issues_missing_required"] += 1
            continue
        record = {
            "id": canonical_issue_id(repo, number, clean_text(row.get("id"))),
            "repo": repo,
            "number": number,
            "title": title,
            "body": clean_text(row.get("body"))[: int(config.get("max_text_characters", 120_000))],
            "state": clean_text(row.get("state")).lower(),
            "author": clean_text(row.get("author")).lower() or None,
            "assignees": sorted({clean_text(x).lower() for x in row.get("assignees") or [] if clean_text(x)}),
            "labels": sorted({clean_text(x).lower() for x in row.get("labels") or [] if clean_text(x)}),
        }
        fingerprint = stable_fingerprint(record, ("repo", "number", "title", "body"))
        if record["id"] in seen_ids or fingerprint in seen_fingerprints:
            stats["issues_duplicate"] += 1
            continue
        seen_ids.add(record["id"]); seen_fingerprints.add(fingerprint)
        output.append(record)
    return output


def preprocess_pulls(rows: list[dict[str, Any]], config: dict[str, Any], stats: Counter) -> list[dict[str, Any]]:
    output: list[dict[str, Any]] = []
    seen_ids: set[str] = set()
    seen_fingerprints: set[str] = set()
    for row in rows:
        repo = clean_text(row.get("repo"))
        number = row.get("number")
        title = clean_text(row.get("title"))
        if not repo or len(title) < int(config.get("min_pr_title_characters", 2)):
            stats["pulls_missing_required"] += 1
            continue
        merge_sha = clean_text(row.get("merge_commit_sha"))
        record = {
            "id": canonical_pr_id(repo, number, clean_text(row.get("id"))),
            "repo": repo,
            "number": number,
            "title": title,
            "body": clean_text(row.get("body"))[: int(config.get("max_text_characters", 120_000))],
            "state": clean_text(row.get("state")).lower(),
            "author": clean_text(row.get("author")).lower() or None,
            "merged": bool(row.get("merged")),
            "merge_commit_sha": canonical_commit_id(repo, merge_sha) if merge_sha else None,
        }
        fingerprint = stable_fingerprint(record, ("repo", "number", "title", "body"))
        if record["id"] in seen_ids or fingerprint in seen_fingerprints:
            stats["pulls_duplicate"] += 1
            continue
        seen_ids.add(record["id"]); seen_fingerprints.add(fingerprint)
        output.append(record)
    return output


def validate_cross_references(directory: Path, stats: Counter) -> None:
    file_ids = {r["id"] for r in read_jsonl(directory / "files.jsonl")}
    commit_ids = {r["id"] for r in read_jsonl(directory / "commits.jsonl")}
    for commit in read_jsonl(directory / "commits.jsonl"):
        for modified in commit.get("modified_files", []):
            if modified.get("file_id") not in file_ids:
                # This is allowed: historical commits can reference deleted files.
                stats["historical_or_deleted_file_references"] += 1
    for pull in read_jsonl(directory / "pulls.jsonl"):
        merge_id = pull.get("merge_commit_sha")
        if merge_id and merge_id not in commit_ids:
            stats["unmined_merge_commit_references"] += 1


def process_directory(source: Path, destination: Path, config: dict[str, Any]) -> dict[str, Any]:
    destination.mkdir(parents=True, exist_ok=True)
    stats: Counter = Counter()
    processors = {
        "files": preprocess_files,
        "commits": preprocess_commits,
        "issues": preprocess_issues,
        "pulls": preprocess_pulls,
    }
    summary: dict[str, Any] = {"source": str(source), "destination": str(destination), "datasets": {}}
    for dataset in DATASETS:
        source_file = source / f"{dataset}.jsonl"
        rows = read_jsonl(source_file)
        cleaned = processors[dataset](rows, config, stats)
        write_jsonl(destination / f"{dataset}.jsonl", cleaned)
        summary["datasets"][dataset] = {
            "input": len(rows),
            "output": len(cleaned),
            "removed": len(rows) - len(cleaned),
        }
    validate_cross_references(destination, stats)
    summary["audit_counts"] = dict(sorted(stats.items()))
    (destination / "preprocessing_report.json").write_text(
        json.dumps(summary, indent=2, ensure_ascii=False), encoding="utf-8"
    )
    return summary


def main() -> None:
    parser = argparse.ArgumentParser(description="Clean and validate repository JSONL before KG construction.")
    parser.add_argument("--config", default="config/preprocessing.yaml")
    parser.add_argument("--include-synthetic", action="store_true")
    parser.add_argument("--overwrite", action="store_true")
    args = parser.parse_args()

    config = yaml.safe_load((ROOT / args.config).read_text(encoding="utf-8"))
    output_root = ROOT / "data" / "processed"
    if args.overwrite and output_root.exists():
        shutil.rmtree(output_root)
    output_root.mkdir(parents=True, exist_ok=True)

    sources = [p for p in (ROOT / "data" / "raw").glob("*") if p.is_dir()]
    if args.include_synthetic:
        sources.append(ROOT / "data" / "synthetic")

    if not sources:
        raise FileNotFoundError("No input directories found in data/raw/. Run ingestion first.")

    all_reports = []
    for source in sorted(sources):
        destination_name = "synthetic" if source.name == "synthetic" else source.name
        report = process_directory(source, output_root / destination_name, config)
        all_reports.append(report)
        counts = report["datasets"]
        print(
            f"{destination_name}: "
            + ", ".join(f"{name} {v['input']}→{v['output']}" for name, v in counts.items())
        )

    combined = {"repositories": all_reports}
    (output_root / "preprocessing_summary.json").write_text(
        json.dumps(combined, indent=2, ensure_ascii=False), encoding="utf-8"
    )
    print(f"Processed data written to: {output_root}")


if __name__ == "__main__":
    main()
